import {test} from 'node:test';
import assert from 'node:assert/strict';
import {initialZone,applyTelemetry,applyPresence,evaluate,act} from './domain.mjs';
import {voiceCommand,voiceEvent,reportSignature,contactText} from './flow.mjs';
const t=Date.parse('2026-10-09T05:00:00Z'),worker={role:'WORKER',sub:'worker'},manager={role:'MANAGER',sub:'manager'};
function checking(managerEnabled=true){
 const z=initialZone('room','dev');Object.assign(z,{t1:5,t2:30,assignedWorkerSub:'worker',assignedPhoneId:'phone',targetWifiSsid:'SITE',managerEnabled,address:'시험 주소',entrance:'시험 출입구'});
 const input=(time,seq,motion)=>({deviceId:'dev',capturedAt:new Date(time).toISOString(),seq,bootId:'boot',motion,motionScore:.1,valid:true});
 applyTelemetry(z,input(t,0,true),t);applyPresence(z,worker,{phoneId:'phone',connection:'CONNECTED',ssid:'SITE'},t);
 applyTelemetry(z,input(t+1000,1,false),t+1000);applyTelemetry(z,input(t+6000,2,false),t+6000);return z;
}
test('report begins during worker check before manager notification',()=>{const z=checking();assert.equal(z.safetyCase.phase,'checking');assert.ok(z.safetyCase.report);assert.equal(z.safetyCase.contact.status,'standby');assert.equal(z.safetyCase.deadline,t+36000);});
test('60 seconds starts at original worker deadline even if evaluator runs late',()=>{const z=checking();evaluate(z,t+50000);assert.equal(z.safetyCase.managerDeadline,t+96000);assert.equal(z.safetyCase.contact.status,'awaiting_manager');evaluate(z,t+96000);assert.equal(z.safetyCase.contact.status,'queued');});
test('manager reading notification or acknowledgement does not extend deadline',()=>{const z=checking();evaluate(z,t+36000);const cmd=voiceCommand(z,manager,{},t+37000);assert.equal(cmd.alertId,z.alerts.find(a=>a.status==='RESCUE').id);voiceEvent(z,manager,{incidentId:z.safetyCase.id,commandId:cmd.id,kind:'received'},t+37000);act(z,manager,'acknowledge',{alertId:cmd.alertId},t+38000);assert.equal(z.safetyCase.contact.status,'awaiting_manager');evaluate(z,t+96000);assert.equal(z.safetyCase.contact.reason,'manager_timeout');});
test('normal manager confirmation cancels queued contact',()=>{const z=checking();evaluate(z,t+96000);act(z,manager,'close',{alertId:z.alerts.find(a=>a.status==='RESCUE').id,reason:'직접 정상 상태 확인'},t+97000);assert.equal(z.safetyCase.contact.status,'cancelled');assert.ok(z.safetyCase.resolvedAt);});
test('worker button before deadline cancels workflow outcome',()=>{const z=checking();act(z,worker,'respond',{},t+20000);evaluate(z,t+96000);assert.equal(z.safetyCase.contact.status,'cancelled');});
test('no manager queues contact at worker deadline',()=>{const z=checking(false);evaluate(z,t+36000);assert.equal(z.safetyCase.contact.reason,'no_manager');assert.equal(z.safetyCase.contact.status,'queued');});
test('explicit help does not wait for manager timeout',()=>{const z=checking();act(z,worker,'help',{quote:'다쳤어요 도와주세요'},t+20000);assert.equal(z.safetyCase.contact.reason,'help_requested');assert.equal(z.safetyCase.contact.status,'queued');});
test('another worker never receives or acknowledges voice checks',()=>{const z=checking();assert.equal(voiceCommand(z,{...worker,sub:'other'},{phoneId:'phone'},t+7000),null);assert.throws(()=>voiceEvent(z,{...worker,sub:'other'},{phoneId:'phone',incidentId:z.safetyCase.id,kind:'spoken'},t+8000));});
test('final warning preempts pending question near deadline',()=>{const z=checking();const q=voiceCommand(z,worker,{phoneId:'phone'},t+7000);assert.equal(q.kind,'check');assert.equal(voiceCommand(z,worker,{phoneId:'phone'},t+30000).kind,'warning');});
test('question completion is idempotent',()=>{const z=checking();const cmd=voiceCommand(z,worker,{phoneId:'phone'},t+7000);const event={phoneId:'phone',incidentId:z.safetyCase.id,commandId:cmd.id,kind:'spoken'};voiceEvent(z,worker,event,t+8000);voiceEvent(z,worker,event,t+8000);assert.equal(z.safetyCase.questionCount,1);});
test('stale AI draft is not used for current contact',()=>{const z=checking();z.safetyCase.report={source:'ai',report_119_ko:'STALE_AI'};z.safetyCase.completedDraftSignature=reportSignature(z.safetyCase);evaluate(z,t+96000);const text=contactText(z.safetyCase);assert.ok(!text.includes('STALE_AI'));assert.match(text,/실제 119 신고 아님/);assert.match(text,/시험 주소/);assert.match(text,/60초/);});
test('ambiguous send becomes unknown instead of a duplicate retry',()=>{const z=checking();Object.assign(z.safetyCase.contact,{status:'sending',attemptedAt:t});evaluate(z,t+31000);assert.equal(z.safetyCase.contact.status,'unknown');});
test('repeat help cannot reset an accepted or ambiguous contact',()=>{for(const status of ['sending','gateway_accepted','unknown']){const z=checking();evaluate(z,t+36000);z.safetyCase.contact.status=status;assert.throws(()=>act(z,manager,'request-help',{alertId:z.alerts.find(a=>a.status==='RESCUE').id},t+40000),/이미 처리/);assert.throws(()=>act(z,worker,'help',{},t+40000),/이미 처리/);assert.equal(z.safetyCase.contact.status,status);}});
test('test recipient cannot be changed to emergency number',()=>{const z=checking();act(z,worker,'respond',{},t+8000);assert.throws(()=>act(z,manager,'settings',{name:'room',area:'',exitGuide:'',targetWifiSsid:'SITE',targetWifiBssid:'',t1:5,t2:30,testRecipient:'119'},t+9000),/시험/);});
test('an unrelated historical rescue cannot cancel or send the current case',()=>{const z=checking();const old={id:'old',status:'RESCUE',caseId:'previous',events:[],closedAt:null};z.alerts.push(old);act(z,manager,'acknowledge',{alertId:'old'},t+7000);assert.equal(z.safetyCase.managerFeedback,null);assert.throws(()=>act(z,manager,'request-help',{alertId:'old'},t+8000),/해당 알림/);act(z,manager,'close',{alertId:'old',reason:'과거 사건 정상 확인'},t+9000);assert.equal(z.safetyCase.resolvedAt,undefined);assert.equal(z.safetyCase.contact.status,'standby');});
test('sensor alert acknowledgement without a personal case is supported',()=>{const z=initialZone();z.alerts=[{id:'sensor',status:'SENSOR_LOST',events:[],closedAt:null}];act(z,manager,'acknowledge',{alertId:'sensor'},t);assert.equal(z.alerts[0].acknowledgedAt,new Date(t).toISOString());assert.equal(z.safetyCase,null);});
