import {test} from 'node:test';import assert from 'node:assert/strict';
import {initialZone} from './domain.mjs';import {applyNative} from './native.mjs';
const t=Date.parse('2026-10-09T05:00:00Z'),id='7a5d2b56c99d48ed';
const event=(kind,extra={})=>({ingest:'native',nativeDeviceId:id,nativeResource:kind,brokerTime:t,...extra});
function ready(){const z=initialZone();applyNative(z,event('health',{status:'ok',online:true,uptime_s:10}),t,id);applyNative(z,event('sensing',{enabled:true,ready:true,mode:'sensing',derived_events_paused:false}),t,id);return z;}
test('calibration without ready output is unavailable rather than no movement',()=>{const z=initialZone();applyNative(z,event('sensing',{enabled:true,ready:false,mode:'sensing',derived_events_paused:false}),t,id);applyNative(z,event('motion',{state:'idle',score:.1,timestamp_ms:10000}),t,id);assert.equal(z.state,'SENSOR_LOST');assert.equal(z.lastValidAt,null);});
test('authenticated physical idle and motion map to monitoring contract',()=>{const z=ready();applyNative(z,event('motion',{state:'motion',score:.9,timestamp_ms:10000}),t,id);assert.equal(z.lastMotionAt,new Date(t).toISOString());assert.equal(z.telemetrySource,'ESPectre native MQTT');});
test('different native device is rejected',()=>{assert.throws(()=>applyNative(ready(),event('motion',{nativeDeviceId:'other'}),t,id),/등록/);});
test('old broker timestamp cannot refresh a signal',()=>{assert.throws(()=>applyNative(ready(),event('motion',{timestamp_ms:10000,state:'idle',score:.1}),t+31000,id),/오래된/);});
test('offline last will marks monitoring unavailable',()=>{const z=ready();applyNative(z,event('motion',{state:'motion',score:.9,timestamp_ms:10000}),t,id);applyNative(z,event('health',{online:false,status:'offline',brokerTime:t+2000}),t+2000,id);assert.equal(z.state,'SENSOR_LOST');});
test('duplicate monotonic events do not refresh sensing',()=>{const z=ready(),input=event('motion',{state:'idle',score:.1,timestamp_ms:10000});applyNative(z,input,t,id);const received=z.lastReceivedAt;applyNative(z,{...input,brokerTime:t+2000},t+2000,id);assert.equal(z.lastReceivedAt,received);});
test('late sensing snapshot cannot clear the newer calibrated state',()=>{const z=ready();applyNative(z,event('sensing',{enabled:true,ready:true,mode:'sensing',derived_events_paused:false,brokerTime:t+2000}),t+2000,id);applyNative(z,event('sensing',{enabled:true,ready:false,mode:'sensing',derived_events_paused:false,brokerTime:t+1000}),t+3000,id);assert.equal(z.nativeSensor.ready,true);});
test('out-of-order motion cannot invent a new boot or replace monotonic progress',()=>{const z=ready();applyNative(z,event('motion',{state:'motion',score:.9,timestamp_ms:12000,brokerTime:t+2000}),t+2000,id);const boot=z.nativeSensor.bootId;applyNative(z,event('motion',{state:'idle',score:.1,timestamp_ms:11000,brokerTime:t+1000}),t+3000,id);assert.equal(z.nativeSensor.bootId,boot);assert.equal(z.nativeSensor.lastMono,12000);});
test('a newer health packet with reset uptime establishes a reboot',()=>{const z=ready();applyNative(z,event('health',{online:true,status:'ok',timestamp_ms:12000,brokerTime:t+100}),t+100,id);applyNative(z,event('motion',{state:'motion',score:.9,timestamp_ms:13000,brokerTime:t+1000}),t+1000,id);applyNative(z,event('health',{online:true,status:'ok',timestamp_ms:100,brokerTime:t+5000}),t+5000,id);assert.equal(z.nativeSensor.lastMono,-1);assert.equal(z.nativeSensor.ready,false);assert.equal(z.lastValidAt,null);});
