import { createRequire } from 'node:module';
import { mkdtemp, rm, mkdir } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { spawn } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';
const require = createRequire(import.meta.url);
const { chromium } = require('C:/Users/User/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const temp = await mkdtemp(path.join(os.tmpdir(), 'stillwatch-flow-'));
const child = spawn(process.execPath, [fileURLToPath(new URL('../server.mjs', import.meta.url))], { env: { ...process.env, PORT: '0', OPENAI_API_KEY: '', STILLWATCH_REPORT_ENABLED: '0', STILLWATCH_SETTINGS_FILE: path.join(temp, '.env'), STILLWATCH_MOBILE_TOKEN_FILE: path.join(temp, 'mobile-token'), STILLWATCH_JOURNAL_FILE: path.join(temp, 'events.json'), STILLWATCH_DEVICE_AUTO_CONNECT: '0' }, stdio: ['ignore', 'pipe', 'pipe'] });
const base = await new Promise((resolve, reject) => { const timeout = setTimeout(() => reject(new Error('startup')), 5000); child.stdout.on('data', data => { const found = data.toString().match(/http:\/\/127\.0\.0\.1:\d+/); if (found) { clearTimeout(timeout); resolve(found[0]); } }); });
const browser = await chromium.launch({ headless: true });
try {
  const page = await browser.newPage({ viewport: { width: 1000, height: 900 } }); const errors = [];
  page.on('pageerror', e => errors.push(e.message)); await page.goto(base);
  await page.locator('#api-status').filter({ hasText: '미설정' }).waitFor();
  await page.locator('#address').fill('시험용 주소'); await page.locator('#still').fill('2'); await page.locator('#response').fill('10'); await page.locator('#manager-seconds').fill('4');
  await page.locator('#start').click(); await page.locator('#still-button').click();
  await page.locator('#status').filter({ hasText: 'CHECKING' }).waitFor();
  await page.locator('#draft').filter({ hasText: '확인 중' }).waitFor();
  assert.equal((await (await page.request.get(base + '/api/state')).json()).incident.notice, null);
  await page.locator('#normal').click(); await page.locator('#status').filter({ hasText: 'WATCHING' }).waitFor();
  await page.locator('#still-button').click(); await page.locator('#status').filter({ hasText: 'CHECKING' }).waitFor();
  await page.locator('#manager-status').filter({ hasText: '피드백 대기' }).waitFor({ timeout: 15000 });
  const before = await (await page.request.get(base + '/api/state')).json();
  await page.locator('[data-feedback=seen]').click();
  assert.equal((await (await page.request.get(base + '/api/state')).json()).incident.managerDeadline, before.incident.managerDeadline);
  await page.locator('#manager-note').fill('테스트에서 작업자 정상 확인'); await page.locator('[data-feedback=normal]').click();
  await page.locator('#status').filter({ hasText: 'WATCHING' }).waitFor();
  const cancelled = await (await page.request.get(base + '/api/state')).json(); assert.equal(cancelled.incidents.at(-1).contact.status, 'cancelled');
  await page.locator('#still-button').click(); await page.locator('#status').filter({ hasText: 'CHECKING' }).waitFor();
  await page.locator('#contact').filter({ hasText: 'recorded' }).waitFor({ timeout: 20000 });
  assert.match(await page.locator('#contact').innerText(), /manager_timeout/); assert.match(await page.locator('#contact').innerText(), /시험용 주소/);
  await page.locator('#pair').click(); await page.waitForFunction(() => /[a-f0-9]{48}/.test(document.querySelector('#pairing').textContent));
  assert.match(await page.locator('#pairing').innerText(), /[a-f0-9]{48}/);
  await page.setViewportSize({ width: 390, height: 844 }); assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await mkdir(new URL('../test-artifacts/', import.meta.url), { recursive: true });
  await page.screenshot({ path: fileURLToPath(new URL('../test-artifacts/functional-flow.png', import.meta.url)), fullPage: true });
  assert.deepEqual(errors, []); console.log('Minimal UI passed: early draft, worker cancellation, manager read/no extension, manager cancellation, timeout outbox, pairing and mobile layout.');
} finally { await browser.close(); const stopped = new Promise(resolve => child.once('close', resolve)); child.kill(); await stopped; await rm(temp, { recursive: true, force: true }); }
